version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  price-api:
    build: .
    ports:
      - "5000:5000"
    command: ["yarn", "test"]
    depends_on:
      - redis
      - mongo
