apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-price-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-pod-service-endpoint
rules:
  - apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:serviceaccount:default:mongo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read-pod-service-endpoint
subjects:
  - kind: ServiceAccount
    name: mongo-price-api
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-price-api
  labels:
    name: mongo-price-api
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo-price-api
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-price-api
spec:
  serviceName: 'mongo-price-api'
  replicas: 2
  selector:
    matchLabels:
      role: mongo-price-api
  template:
    metadata:
      labels:
        role: mongo-price-api
    spec:
      serviceAccountName: mongo-price-api
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: mongo-price-api
          image: mongo:4
          command:
            - mongod
          args:
            - '--replSet=rs0'
            - '--bind_ip=0.0.0.0'
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-price-api-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: morphy/k8s-mongo-sidecar
          env:
            - name: KUBERNETES_POD_LABELS
              value: 'role=mongo-price-api'
            - name: KUBERNETES_SERVICE_NAME
              value: 'mongo-price-api'
  volumeClaimTemplates:
    - metadata:
        name: mongo-price-api-persistent-storage
      spec:
        accessModes: ['ReadWriteOnce']
        resources:
          requests:
            storage: 1Gi
