name: Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build, push, and
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t saulmaldonado/cryptotracker-graphql-price-api:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub Container Registry
        run: docker push saulmaldonado/cryptotracker-graphql-price-api

      - name: Get current image name
        run: export OLD_IMAGE_NAME=$(kubectl get deployment price-api -o jsonpath="{.spec.template.spec.containers[0].image}")

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|${OLD_IMAGE_NAME}|saulmaldonado/cryptotracker-graphql-price-api:'${TAG}'|' $GITHUB_WORKSPACE/k8s/graphQLServerDeployment.yaml

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save crypto-tracker

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/k8s/graphQLServerDeployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/price-api
