# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Integration

on:
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: node
    strategy:
      matrix:
        node: ['14.x', '15.x']
    services:
      redis:
        image: saulmaldonado/crypto-tracker-redis-test:2.0.0
      mongo:
        image: mongo:4.4
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: test
        run: yarn test:CI
        env:
          MONGO_URI: mongodb://mongo:27017
          REDIS_HOST: redis
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
          AUTH0_API_ID: ${{secrets.AUTH0_API_ID}}
          AUTH0_API_SECRET: ${{secrets.AUTH0_API_SECRET}}
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
          AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
          AUTH0_CONNECTION: ${{secrets.AUTH0_CONNECTION}}
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_MANAGEMENT_AUDIENCE: ${{secrets.AUTH0_MANAGEMENT_AUDIENCE}}
          AUTH0_MANAGEMENT_CLIENT_ID: ${{secrets.AUTH0_MANAGEMENT_CLIENT_ID}}
          AUTH0_MANAGEMENT_SECRET: ${{secrets.AUTH0_MANAGEMENT_SECRET}}
          NOMICS_API_KEY: ${{secrets.NOMICS_API_KEY}}
      - uses: codecov/codecov-action@v1
