# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install
      run: yarn --frozen-lockfile
    - name: Test
      run: yarn test
      env: 
        AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
        AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
        AUTH0_API_ID: ${{secrets.AUTH0_API_ID}}
        AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
        AUTH0_API_SECRET: ${{secrets.AUTH0_API_SECRET}}
        AUTH0_CONNECTION: ${{secrets.AUTH0_CONNECTION}}
        AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
        AUTH0_MANAGEMENT_AUDIENCE: ${{secrets.AUTH0_MANAGEMENT_AUDIENCE}}
        AUTH0_MANAGEMENT_SECRET: ${{secrets.AUTH0_MANAGEMENT_SECRET}}
        AUTH0_MANAGEMENT_CLIENT_ID: ${{secrets.AUTH0_MANAGEMENT_CLIENT_ID}}
        NOMICS_API_KEY: ${{secrets.NOMICS_API_KEY}}
        API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
