# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: node
    services:
      redis:
        image: redis:alpine
      mongo:
        image: mongo
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: test
        run: yarn test:CI --runInBand
        env:
          MONGO_URI: mongodb://mongo:27017
          REDIS_HOST: redis
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
          AUTH0_API_ID: ${{secrets.AUTH0_API_ID}}
          AUTH0_API_SECRET: ${{secrets.AUTH0_API_SECRET}}
          AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
          AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
          AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
          AUTH0_CONNECTION: ${{secrets.AUTH0_CONNECTION}}
          AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}}
          AUTH0_MANAGEMENT_AUDIENCE: ${{secrets.AUTH0_MANAGEMENT_AUDIENCE}}
          AUTH0_MANAGEMENT_CLIENT_ID: ${{secrets.AUTH0_MANAGEMENT_CLIENT_ID}}
          AUTH0_MANAGEMENT_SECRET: ${{secrets.AUTH0_MANAGEMENT_SECRET}}
          NOMICS_API_KEY: ${{secrets.NOMICS_API_KEY}}

      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
