# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:alpine
    services:
      redis:
        image: redis:alpine
      mongo:
        image: mongo
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Dotenv Action
        uses: falti/dotenv-action@v0.2.4

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: test
        run: yarn test
        env:
          MONGO_URI: mongodb://mongo
          REDIS_HOST: redis
